Repository map-of-pi/map-of-pi-backend, pull requests merged in 2025-07, with the labels that each got.

#271 Ft/notification
  src/config/docs/NotificationsSchema.yml
  src/controllers/notificationController.ts
  src/controllers/orderController.ts
  src/controllers/sellerController.ts
  src/models/Notification.ts
  src/routes/notification.routes.ts
  src/services/notification.service.ts
  src/types.ts
  src/utils/app.ts
  test/controllers/notificationController.spec.ts
  test/services/notification.service.spec.ts
Labels: in progress

#284 (Online shop) Sales Item: Updating Stock-level
  src/errors/StockValidationError.ts
  src/helpers/order.ts
  src/services/order.service.ts
  test/helpers/order.spec.ts
  test/jest.setup.ts
  test/services/order.service.spec.ts
Labels: pending-c/o-feedback

#285 (Online shop): online ordering only release
  src/controllers/orderController.ts
  src/helpers/payment.ts
  src/models/Order.ts
  src/routes/order.routes.ts
  src/services/order.service.ts
  test/controllers/orderController.spec.ts
  test/helpers/payment.spec.ts
  test/services/order.service.spec.ts
Labels: pending-c/o-feedback

#290 Notifications: Notification popup appeared, but zero in list screen
  src/controllers/notificationController.ts
  src/routes/notification.routes.ts
  src/services/notification.service.ts
  test/controllers/notificationController.spec.ts
  test/services/notification.service.spec.ts
Labels: Ready for review
